### ISSUE TITLE
No longer working with Moodle 2.9Beta

### ISSUE THREAD

**Issue by dthies** [andrewnicols/moodle-atto_htmlplus#2]
Hi Andrew,
I have not been able to use this with the latest branch 2.9 Beta.  It is throwing a javascript exception which prevents the editor from loading.  Adding window. to  codeMirror in wrapper.js allows loading, but there is another exception when the button is pressed.

**Comment by tonyjbutler** [comment]
Still not working in 2.9 stable:
Uncaught ReferenceError: CodeMirror is not defined

**Comment by heylael** [comment]
I'm getting the same error on Moodle 2.9.1+ 
Is there a fix for this?
